[tool.coverage.run]
branch = true

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",
    ]

fail_under = 100
skip_empty = true
ignore_errors = true

[tool.black]
line-length = 88
